name: eval-ci
on: [push, pull_request]
jobs:
  cpu-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build evaluator (CPU) & run tests
        run: |
          docker build -t hb-eval ./evaluator \
            --build-arg SIMPLE_EVALS_COMMIT=1b9e4ac
          docker run --rm hb-eval -m pytest -q
